services:
  redis:
    image: redis:7.0-alpine
    container_name: dify_wp_sync_redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    build: .
    container_name: dify_wp_sync_app
    # Load vars from .env file
    env_file: 
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
