version: '3.9'
services:
  redis:
    image: redis:7.0-alpine
    container_name: dify_wp_sync_redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    build: .
    container_name: dify_wp_sync_app
    environment:

      WPCOM_CLIENT_ID: ${WPCOM_CLIENT_ID}
      WPCOM_CLIENT_SECRET: ${WPCOM_CLIENT_SECRET}
      WPCOM_REDIRECT_URI: ${WPCOM_REDIRECT_URI}
      DIFY_BASE_URL: ${DIFY_BASE_URL:-https://api.dify.ai/v1}
      DIFY_API_KEY: ${DIFY_API_KEY}
      REDIS_ADDR: ${REDIS_ADDR:-redis:6379}

      REDIS_DB: 0
      REDIS_PASSWORD: ""

      # Server port
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
